### ISSUE TITLE
Which system？Linux？Windows？

### ISSUE THREAD

**Issue by Pythonpa** [Rockyzsu/zhihuToKindle#2]
Which system？Linux？Windows？

**Comment by Rockyzsu** [comment]
Both work.

**Comment by Pythonpa** [comment]
Thank you~~算了，不用英文了，最近烦工作的事情，没有开Gmail,才看到你的回信，很抱歉，同样也很感谢啊。

2017-02-21 17:04 GMT+08:00 Rocky Chen <notifications@github.com>:
